services:
  database:
    image: mysql:latest
    container_name: number8
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: number8
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

volumes:
  mysql_data:

networks:
  my_network:
